# +----------------------------------------------------------------------------+
# | CTT-demo v0.1 * transistor tester and characteristic curve plotter         |
# | Copyright (C) 2010-2022 Pozsar Zsolt <pozsarzs@gmail.com>                  |
# | Makefile                                                                   |
# | Make file for FreePascal source.                                           |
# +----------------------------------------------------------------------------+

all:
	@ppc386 ctt.lpr
	@echo "Done."

clean:
	@rm --force *.o *.ppu ctt
	@echo "Done."
